// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr2J9CC_LtuqvNxIWgzRiXD1U7tFQtDgE',
    appId: '1:307639370026:web:0ddd079a2c4a8125989e53',
    messagingSenderId: '307639370026',
    projectId: 'sorteos-micro',
    authDomain: 'sorteos-micro.firebaseapp.com',
    storageBucket: 'sorteos-micro.firebasestorage.app',
    measurementId: 'G-QCX7347YCJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAiceytoBUbQOHVwwe4Xvzqw4VN70m3LU',
    appId: '1:307639370026:android:b38336c339b878b7989e53',
    messagingSenderId: '307639370026',
    projectId: 'sorteos-micro',
    storageBucket: 'sorteos-micro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBh53-DDKQY1Ar5Xj_MwoDRBmGI_gUEaZE',
    appId: '1:307639370026:ios:d9b0eba21015331b989e53',
    messagingSenderId: '307639370026',
    projectId: 'sorteos-micro',
    storageBucket: 'sorteos-micro.firebasestorage.app',
    iosBundleId: 'com.example.sorteos-micr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBh53-DDKQY1Ar5Xj_MwoDRBmGI_gUEaZE',
    appId: '1:307639370026:ios:612b53e530b5411e989e53',
    messagingSenderId: '307639370026',
    projectId: 'sorteos-micro',
    storageBucket: 'sorteos-micro.firebasestorage.app',
    iosBundleId: 'com.example.sorteos-micro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBr2J9CC_LtuqvNxIWgzRiXD1U7tFQtDgE',
    appId: '1:307639370026:web:52c3c032689bf950989e53',
    messagingSenderId: '307639370026',
    projectId: 'sorteos-micro',
    authDomain: 'sorteos-micro.firebaseapp.com',
    storageBucket: 'sorteos-micro.firebasestorage.app',
    measurementId: 'G-650HK68VQW',
  );
}
